# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Lei\BlackPearl_Platform_20200909\BlackPearl_UI\BlackPearl.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(930, 481)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.system_frame = QtWidgets.QFrame(self.centralWidget)
        self.system_frame.setGeometry(QtCore.QRect(10, 10, 211, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.system_frame.sizePolicy().hasHeightForWidth())
        self.system_frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.system_frame.setFont(font)
        self.system_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.system_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.system_frame.setObjectName("system_frame")
        self.system_groupBox = QtWidgets.QGroupBox(self.system_frame)
        self.system_groupBox.setGeometry(QtCore.QRect(10, 10, 191, 81))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.system_groupBox.setFont(font)
        self.system_groupBox.setObjectName("system_groupBox")
        self.serial_port_title_label = QtWidgets.QLabel(self.system_groupBox)
        self.serial_port_title_label.setGeometry(QtCore.QRect(10, 20, 80, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_port_title_label.sizePolicy().hasHeightForWidth())
        self.serial_port_title_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.serial_port_title_label.setFont(font)
        self.serial_port_title_label.setObjectName("serial_port_title_label")
        self.serial_port_comboBox = QtWidgets.QComboBox(self.system_groupBox)
        self.serial_port_comboBox.setEnabled(True)
        self.serial_port_comboBox.setGeometry(QtCore.QRect(100, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.serial_port_comboBox.setFont(font)
        self.serial_port_comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.serial_port_comboBox.setCurrentText("Scanning")
        self.serial_port_comboBox.setObjectName("serial_port_comboBox")
        self.serial_port_comboBox.addItem("")
        self.serial_port_comboBox.addItem("")
        self.serial_status_label = QtWidgets.QLabel(self.system_groupBox)
        self.serial_status_label.setGeometry(QtCore.QRect(10, 50, 80, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_status_label.sizePolicy().hasHeightForWidth())
        self.serial_status_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.serial_status_label.setFont(font)
        self.serial_status_label.setObjectName("serial_status_label")
        self.serial_status_title_label = QtWidgets.QLabel(self.system_groupBox)
        self.serial_status_title_label.setGeometry(QtCore.QRect(100, 50, 81, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_status_title_label.sizePolicy().hasHeightForWidth())
        self.serial_status_title_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.serial_status_title_label.setFont(font)
        self.serial_status_title_label.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.serial_status_title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.serial_status_title_label.setObjectName("serial_status_title_label")
        self.chip_frame = QtWidgets.QFrame(self.centralWidget)
        self.chip_frame.setEnabled(True)
        self.chip_frame.setGeometry(QtCore.QRect(10, 120, 211, 351))
        self.chip_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chip_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.chip_frame.setObjectName("chip_frame")
        self.dac_groupBox = QtWidgets.QGroupBox(self.chip_frame)
        self.dac_groupBox.setGeometry(QtCore.QRect(10, 140, 191, 201))
        self.dac_groupBox.setObjectName("dac_groupBox")
        self.dac_rst_spinBox = QtWidgets.QSpinBox(self.dac_groupBox)
        self.dac_rst_spinBox.setGeometry(QtCore.QRect(90, 20, 91, 21))
        self.dac_rst_spinBox.setMaximum(1800)
        self.dac_rst_spinBox.setObjectName("dac_rst_spinBox")
        self.dac_y_spinBox = QtWidgets.QSpinBox(self.dac_groupBox)
        self.dac_y_spinBox.setGeometry(QtCore.QRect(90, 50, 91, 21))
        self.dac_y_spinBox.setMaximum(1800)
        self.dac_y_spinBox.setObjectName("dac_y_spinBox")
        self.dac_rst_label = QtWidgets.QLabel(self.dac_groupBox)
        self.dac_rst_label.setGeometry(QtCore.QRect(10, 20, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dac_rst_label.sizePolicy().hasHeightForWidth())
        self.dac_rst_label.setSizePolicy(sizePolicy)
        self.dac_rst_label.setObjectName("dac_rst_label")
        self.dac_y_label = QtWidgets.QLabel(self.dac_groupBox)
        self.dac_y_label.setGeometry(QtCore.QRect(10, 50, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dac_y_label.sizePolicy().hasHeightForWidth())
        self.dac_y_label.setSizePolicy(sizePolicy)
        self.dac_y_label.setObjectName("dac_y_label")
        self.dac_iv_label = QtWidgets.QLabel(self.dac_groupBox)
        self.dac_iv_label.setGeometry(QtCore.QRect(10, 80, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dac_iv_label.sizePolicy().hasHeightForWidth())
        self.dac_iv_label.setSizePolicy(sizePolicy)
        self.dac_iv_label.setObjectName("dac_iv_label")
        self.dac_iv_spinBox = QtWidgets.QSpinBox(self.dac_groupBox)
        self.dac_iv_spinBox.setGeometry(QtCore.QRect(90, 80, 91, 21))
        self.dac_iv_spinBox.setMaximum(1800)
        self.dac_iv_spinBox.setObjectName("dac_iv_spinBox")
        self.dac_ota_label = QtWidgets.QLabel(self.dac_groupBox)
        self.dac_ota_label.setGeometry(QtCore.QRect(10, 110, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dac_ota_label.sizePolicy().hasHeightForWidth())
        self.dac_ota_label.setSizePolicy(sizePolicy)
        self.dac_ota_label.setObjectName("dac_ota_label")
        self.dac_ota_spinBox = QtWidgets.QSpinBox(self.dac_groupBox)
        self.dac_ota_spinBox.setGeometry(QtCore.QRect(90, 110, 91, 21))
        self.dac_ota_spinBox.setMaximum(1800)
        self.dac_ota_spinBox.setObjectName("dac_ota_spinBox")
        self.dac_int_label = QtWidgets.QLabel(self.dac_groupBox)
        self.dac_int_label.setGeometry(QtCore.QRect(10, 140, 71, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dac_int_label.sizePolicy().hasHeightForWidth())
        self.dac_int_label.setSizePolicy(sizePolicy)
        self.dac_int_label.setObjectName("dac_int_label")
        self.dac_int_spinBox = QtWidgets.QSpinBox(self.dac_groupBox)
        self.dac_int_spinBox.setGeometry(QtCore.QRect(90, 140, 91, 21))
        self.dac_int_spinBox.setMaximum(1800)
        self.dac_int_spinBox.setObjectName("dac_int_spinBox")
        self.dac_read_pushButton = QtWidgets.QPushButton(self.dac_groupBox)
        self.dac_read_pushButton.setGeometry(QtCore.QRect(70, 170, 51, 21))
        self.dac_read_pushButton.setObjectName("dac_read_pushButton")
        self.dac_write_pushButton = QtWidgets.QPushButton(self.dac_groupBox)
        self.dac_write_pushButton.setGeometry(QtCore.QRect(130, 170, 51, 21))
        self.dac_write_pushButton.setObjectName("dac_write_pushButton")
        self.dac_reset_pushButton = QtWidgets.QPushButton(self.dac_groupBox)
        self.dac_reset_pushButton.setGeometry(QtCore.QRect(10, 170, 51, 21))
        self.dac_reset_pushButton.setObjectName("dac_reset_pushButton")
        self.profile_groupBox = QtWidgets.QGroupBox(self.chip_frame)
        self.profile_groupBox.setGeometry(QtCore.QRect(10, 10, 191, 121))
        self.profile_groupBox.setObjectName("profile_groupBox")
        self.chip_delay_title_label = QtWidgets.QLabel(self.profile_groupBox)
        self.chip_delay_title_label.setGeometry(QtCore.QRect(20, 80, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chip_delay_title_label.sizePolicy().hasHeightForWidth())
        self.chip_delay_title_label.setSizePolicy(sizePolicy)
        self.chip_delay_title_label.setObjectName("chip_delay_title_label")
        self.chip_delay_spinBox = QtWidgets.QSpinBox(self.profile_groupBox)
        self.chip_delay_spinBox.setGeometry(QtCore.QRect(110, 80, 71, 21))
        self.chip_delay_spinBox.setMaximum(15)
        self.chip_delay_spinBox.setObjectName("chip_delay_spinBox")
        self.chip_id_title_label = QtWidgets.QLabel(self.profile_groupBox)
        self.chip_id_title_label.setGeometry(QtCore.QRect(20, 20, 91, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chip_id_title_label.sizePolicy().hasHeightForWidth())
        self.chip_id_title_label.setSizePolicy(sizePolicy)
        self.chip_id_title_label.setObjectName("chip_id_title_label")
        self.chip_id_comboBox = QtWidgets.QComboBox(self.profile_groupBox)
        self.chip_id_comboBox.setEnabled(True)
        self.chip_id_comboBox.setGeometry(QtCore.QRect(110, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.chip_id_comboBox.setFont(font)
        self.chip_id_comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chip_id_comboBox.setCurrentText("0")
        self.chip_id_comboBox.setObjectName("chip_id_comboBox")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_id_comboBox.addItem("")
        self.chip_frequency_title_label = QtWidgets.QLabel(self.profile_groupBox)
        self.chip_frequency_title_label.setGeometry(QtCore.QRect(20, 50, 91, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chip_frequency_title_label.sizePolicy().hasHeightForWidth())
        self.chip_frequency_title_label.setSizePolicy(sizePolicy)
        self.chip_frequency_title_label.setObjectName("chip_frequency_title_label")
        self.chip_frequency_comboBox = QtWidgets.QComboBox(self.profile_groupBox)
        self.chip_frequency_comboBox.setEnabled(True)
        self.chip_frequency_comboBox.setGeometry(QtCore.QRect(110, 50, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.chip_frequency_comboBox.setFont(font)
        self.chip_frequency_comboBox.setToolTip("")
        self.chip_frequency_comboBox.setStatusTip("")
        self.chip_frequency_comboBox.setWhatsThis("")
        self.chip_frequency_comboBox.setAccessibleName("")
        self.chip_frequency_comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chip_frequency_comboBox.setObjectName("chip_frequency_comboBox")
        self.chip_frequency_comboBox.addItem("")
        self.chip_frequency_comboBox.addItem("")
        self.chip_frequency_comboBox.addItem("")
        self.chip_frequency_comboBox.addItem("")
        self.chip_frequency_comboBox.addItem("")
        self.rt_frame = QtWidgets.QFrame(self.centralWidget)
        self.rt_frame.setGeometry(QtCore.QRect(230, 10, 331, 251))
        self.rt_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rt_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rt_frame.setObjectName("rt_frame")
        self.rt_groupBox = QtWidgets.QGroupBox(self.rt_frame)
        self.rt_groupBox.setGeometry(QtCore.QRect(10, 10, 311, 231))
        self.rt_groupBox.setObjectName("rt_groupBox")
        self.rt_path_lineEdit = QtWidgets.QLineEdit(self.rt_groupBox)
        self.rt_path_lineEdit.setGeometry(QtCore.QRect(10, 40, 251, 16))
        self.rt_path_lineEdit.setReadOnly(True)
        self.rt_path_lineEdit.setObjectName("rt_path_lineEdit")
        self.rt_path_title_label = QtWidgets.QLabel(self.rt_groupBox)
        self.rt_path_title_label.setGeometry(QtCore.QRect(10, 20, 291, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rt_path_title_label.sizePolicy().hasHeightForWidth())
        self.rt_path_title_label.setSizePolicy(sizePolicy)
        self.rt_path_title_label.setObjectName("rt_path_title_label")
        self.rt_path_toolButton = QtWidgets.QToolButton(self.rt_groupBox)
        self.rt_path_toolButton.setGeometry(QtCore.QRect(270, 40, 31, 16))
        self.rt_path_toolButton.setObjectName("rt_path_toolButton")
        self.rt_info_title_label = QtWidgets.QLabel(self.rt_groupBox)
        self.rt_info_title_label.setGeometry(QtCore.QRect(10, 60, 291, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rt_info_title_label.sizePolicy().hasHeightForWidth())
        self.rt_info_title_label.setSizePolicy(sizePolicy)
        self.rt_info_title_label.setObjectName("rt_info_title_label")
        self.rt_chip_id_title_label = QtWidgets.QLabel(self.rt_groupBox)
        self.rt_chip_id_title_label.setGeometry(QtCore.QRect(20, 80, 121, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rt_chip_id_title_label.sizePolicy().hasHeightForWidth())
        self.rt_chip_id_title_label.setSizePolicy(sizePolicy)
        self.rt_chip_id_title_label.setObjectName("rt_chip_id_title_label")
        self.rt_chip_id_spinBox = QtWidgets.QSpinBox(self.rt_groupBox)
        self.rt_chip_id_spinBox.setGeometry(QtCore.QRect(150, 80, 51, 18))
        self.rt_chip_id_spinBox.setMaximum(99)
        self.rt_chip_id_spinBox.setObjectName("rt_chip_id_spinBox")
        self.rt_user_com_title_label = QtWidgets.QLabel(self.rt_groupBox)
        self.rt_user_com_title_label.setGeometry(QtCore.QRect(20, 120, 121, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rt_user_com_title_label.sizePolicy().hasHeightForWidth())
        self.rt_user_com_title_label.setSizePolicy(sizePolicy)
        self.rt_user_com_title_label.setObjectName("rt_user_com_title_label")
        self.rt_user_com_lineEdit = QtWidgets.QLineEdit(self.rt_groupBox)
        self.rt_user_com_lineEdit.setGeometry(QtCore.QRect(150, 120, 151, 18))
        self.rt_user_com_lineEdit.setText("")
        self.rt_user_com_lineEdit.setReadOnly(False)
        self.rt_user_com_lineEdit.setObjectName("rt_user_com_lineEdit")
        self.rt_readout_pushButton = QtWidgets.QPushButton(self.rt_groupBox)
        self.rt_readout_pushButton.setGeometry(QtCore.QRect(250, 150, 51, 21))
        self.rt_readout_pushButton.setToolTip("")
        self.rt_readout_pushButton.setObjectName("rt_readout_pushButton")
        self.rt_save_checkBox = QtWidgets.QCheckBox(self.rt_groupBox)
        self.rt_save_checkBox.setGeometry(QtCore.QRect(200, 150, 51, 21))
        self.rt_save_checkBox.setChecked(True)
        self.rt_save_checkBox.setObjectName("rt_save_checkBox")
        self.rt_offset_pushButton = QtWidgets.QPushButton(self.rt_groupBox)
        self.rt_offset_pushButton.setGeometry(QtCore.QRect(10, 150, 51, 21))
        self.rt_offset_pushButton.setToolTip("")
        self.rt_offset_pushButton.setObjectName("rt_offset_pushButton")
        self.rt_exp_id_title_label = QtWidgets.QLabel(self.rt_groupBox)
        self.rt_exp_id_title_label.setGeometry(QtCore.QRect(20, 100, 121, 18))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rt_exp_id_title_label.sizePolicy().hasHeightForWidth())
        self.rt_exp_id_title_label.setSizePolicy(sizePolicy)
        self.rt_exp_id_title_label.setObjectName("rt_exp_id_title_label")
        self.rt_exp_id_spinBox = QtWidgets.QSpinBox(self.rt_groupBox)
        self.rt_exp_id_spinBox.setGeometry(QtCore.QRect(150, 100, 51, 18))
        self.rt_exp_id_spinBox.setMaximum(99)
        self.rt_exp_id_spinBox.setObjectName("rt_exp_id_spinBox")
        self.rt_debug_checkBox = QtWidgets.QCheckBox(self.rt_groupBox)
        self.rt_debug_checkBox.setGeometry(QtCore.QRect(250, 80, 51, 21))
        self.rt_debug_checkBox.setObjectName("rt_debug_checkBox")
        self.rt_pixel_title_label = QtWidgets.QLabel(self.rt_groupBox)
        self.rt_pixel_title_label.setGeometry(QtCore.QRect(10, 180, 141, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rt_pixel_title_label.sizePolicy().hasHeightForWidth())
        self.rt_pixel_title_label.setSizePolicy(sizePolicy)
        self.rt_pixel_title_label.setObjectName("rt_pixel_title_label")
        self.rt_row_spinBox = QtWidgets.QSpinBox(self.rt_groupBox)
        self.rt_row_spinBox.setGeometry(QtCore.QRect(10, 200, 41, 18))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.rt_row_spinBox.setFont(font)
        self.rt_row_spinBox.setMaximum(127)
        self.rt_row_spinBox.setSingleStep(1)
        self.rt_row_spinBox.setProperty("value", 63)
        self.rt_row_spinBox.setObjectName("rt_row_spinBox")
        self.rt_col_spinBox = QtWidgets.QSpinBox(self.rt_groupBox)
        self.rt_col_spinBox.setGeometry(QtCore.QRect(60, 200, 41, 18))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.rt_col_spinBox.setFont(font)
        self.rt_col_spinBox.setMaximum(127)
        self.rt_col_spinBox.setProperty("value", 63)
        self.rt_col_spinBox.setObjectName("rt_col_spinBox")
        self.rt_off_pushButton = QtWidgets.QPushButton(self.rt_groupBox)
        self.rt_off_pushButton.setGeometry(QtCore.QRect(250, 200, 51, 21))
        self.rt_off_pushButton.setToolTip("")
        self.rt_off_pushButton.setObjectName("rt_off_pushButton")
        self.console_frame = QtWidgets.QFrame(self.centralWidget)
        self.console_frame.setGeometry(QtCore.QRect(570, 10, 351, 461))
        self.console_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.console_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.console_frame.setObjectName("console_frame")
        self.console_groupBox = QtWidgets.QGroupBox(self.console_frame)
        self.console_groupBox.setGeometry(QtCore.QRect(10, 10, 331, 381))
        self.console_groupBox.setObjectName("console_groupBox")
        self.console_clear_pushButton = QtWidgets.QPushButton(self.console_groupBox)
        self.console_clear_pushButton.setGeometry(QtCore.QRect(260, 350, 61, 21))
        self.console_clear_pushButton.setObjectName("console_clear_pushButton")
        self.console_textEdit = QtWidgets.QTextBrowser(self.console_groupBox)
        self.console_textEdit.setGeometry(QtCore.QRect(10, 20, 311, 321))
        self.console_textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.console_textEdit.setObjectName("console_textEdit")
        self.console_progressBar = QtWidgets.QProgressBar(self.console_groupBox)
        self.console_progressBar.setGeometry(QtCore.QRect(10, 350, 241, 21))
        self.console_progressBar.setMaximum(100)
        self.console_progressBar.setProperty("value", 0)
        self.console_progressBar.setObjectName("console_progressBar")
        self.user_cmd_groupBox = QtWidgets.QGroupBox(self.console_frame)
        self.user_cmd_groupBox.setGeometry(QtCore.QRect(10, 400, 331, 51))
        self.user_cmd_groupBox.setObjectName("user_cmd_groupBox")
        self.user_cmd_lineEdit = QtWidgets.QLineEdit(self.user_cmd_groupBox)
        self.user_cmd_lineEdit.setGeometry(QtCore.QRect(10, 20, 241, 22))
        self.user_cmd_lineEdit.setWhatsThis("")
        self.user_cmd_lineEdit.setPlaceholderText("")
        self.user_cmd_lineEdit.setObjectName("user_cmd_lineEdit")
        self.user_cmd_pushButton = QtWidgets.QPushButton(self.user_cmd_groupBox)
        self.user_cmd_pushButton.setGeometry(QtCore.QRect(260, 20, 61, 21))
        self.user_cmd_pushButton.setObjectName("user_cmd_pushButton")
        self.processing_frame = QtWidgets.QFrame(self.centralWidget)
        self.processing_frame.setGeometry(QtCore.QRect(230, 270, 331, 201))
        self.processing_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.processing_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.processing_frame.setObjectName("processing_frame")
        self.tabWidget = QtWidgets.QTabWidget(self.processing_frame)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 311, 181))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.file_tab = QtWidgets.QWidget()
        self.file_tab.setObjectName("file_tab")
        self.concatenation_path_title_label = QtWidgets.QLabel(self.file_tab)
        self.concatenation_path_title_label.setGeometry(QtCore.QRect(10, 10, 281, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.concatenation_path_title_label.sizePolicy().hasHeightForWidth())
        self.concatenation_path_title_label.setSizePolicy(sizePolicy)
        self.concatenation_path_title_label.setObjectName("concatenation_path_title_label")
        self.concatenation_path_lineEdit = QtWidgets.QLineEdit(self.file_tab)
        self.concatenation_path_lineEdit.setGeometry(QtCore.QRect(10, 30, 251, 16))
        self.concatenation_path_lineEdit.setReadOnly(True)
        self.concatenation_path_lineEdit.setObjectName("concatenation_path_lineEdit")
        self.concatenation_path_toolButton = QtWidgets.QToolButton(self.file_tab)
        self.concatenation_path_toolButton.setGeometry(QtCore.QRect(270, 30, 31, 16))
        self.concatenation_path_toolButton.setObjectName("concatenation_path_toolButton")
        self.concatenation_pushButton = QtWidgets.QPushButton(self.file_tab)
        self.concatenation_pushButton.setGeometry(QtCore.QRect(250, 60, 51, 20))
        self.concatenation_pushButton.setToolTip("")
        self.concatenation_pushButton.setObjectName("concatenation_pushButton")
        self.tabWidget.addTab(self.file_tab, "")
        self.replay_tab = QtWidgets.QWidget()
        self.replay_tab.setObjectName("replay_tab")
        self.replay_path_title_label = QtWidgets.QLabel(self.replay_tab)
        self.replay_path_title_label.setGeometry(QtCore.QRect(10, 10, 291, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replay_path_title_label.sizePolicy().hasHeightForWidth())
        self.replay_path_title_label.setSizePolicy(sizePolicy)
        self.replay_path_title_label.setObjectName("replay_path_title_label")
        self.replay_path_lineEdit = QtWidgets.QLineEdit(self.replay_tab)
        self.replay_path_lineEdit.setGeometry(QtCore.QRect(10, 30, 251, 16))
        self.replay_path_lineEdit.setReadOnly(True)
        self.replay_path_lineEdit.setObjectName("replay_path_lineEdit")
        self.replay_path_toolButton = QtWidgets.QToolButton(self.replay_tab)
        self.replay_path_toolButton.setGeometry(QtCore.QRect(270, 30, 31, 16))
        self.replay_path_toolButton.setObjectName("replay_path_toolButton")
        self.replay_check_pushButton = QtWidgets.QPushButton(self.replay_tab)
        self.replay_check_pushButton.setGeometry(QtCore.QRect(170, 130, 51, 20))
        self.replay_check_pushButton.setObjectName("replay_check_pushButton")
        self.replay_start_lineEdit = QtWidgets.QLineEdit(self.replay_tab)
        self.replay_start_lineEdit.setGeometry(QtCore.QRect(70, 60, 81, 16))
        self.replay_start_lineEdit.setReadOnly(False)
        self.replay_start_lineEdit.setObjectName("replay_start_lineEdit")
        self.replay_step_horizontalSlider = QtWidgets.QSlider(self.replay_tab)
        self.replay_step_horizontalSlider.setGeometry(QtCore.QRect(160, 100, 131, 16))
        self.replay_step_horizontalSlider.setMinimum(1)
        self.replay_step_horizontalSlider.setMaximum(10000)
        self.replay_step_horizontalSlider.setSingleStep(10)
        self.replay_step_horizontalSlider.setPageStep(1)
        self.replay_step_horizontalSlider.setProperty("value", 1)
        self.replay_step_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.replay_step_horizontalSlider.setObjectName("replay_step_horizontalSlider")
        self.replay_start_title_label = QtWidgets.QLabel(self.replay_tab)
        self.replay_start_title_label.setGeometry(QtCore.QRect(10, 60, 51, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replay_start_title_label.sizePolicy().hasHeightForWidth())
        self.replay_start_title_label.setSizePolicy(sizePolicy)
        self.replay_start_title_label.setObjectName("replay_start_title_label")
        self.replay_end_horizontalSlider = QtWidgets.QSlider(self.replay_tab)
        self.replay_end_horizontalSlider.setGeometry(QtCore.QRect(160, 80, 131, 16))
        self.replay_end_horizontalSlider.setMinimum(1)
        self.replay_end_horizontalSlider.setMaximum(100)
        self.replay_end_horizontalSlider.setPageStep(1)
        self.replay_end_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.replay_end_horizontalSlider.setObjectName("replay_end_horizontalSlider")
        self.replay_end_title_label = QtWidgets.QLabel(self.replay_tab)
        self.replay_end_title_label.setGeometry(QtCore.QRect(10, 80, 51, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replay_end_title_label.sizePolicy().hasHeightForWidth())
        self.replay_end_title_label.setSizePolicy(sizePolicy)
        self.replay_end_title_label.setObjectName("replay_end_title_label")
        self.replay_step_lineEdit = QtWidgets.QLineEdit(self.replay_tab)
        self.replay_step_lineEdit.setGeometry(QtCore.QRect(70, 100, 81, 16))
        self.replay_step_lineEdit.setReadOnly(False)
        self.replay_step_lineEdit.setObjectName("replay_step_lineEdit")
        self.replay_start_horizontalSlider = QtWidgets.QSlider(self.replay_tab)
        self.replay_start_horizontalSlider.setGeometry(QtCore.QRect(160, 60, 131, 16))
        self.replay_start_horizontalSlider.setMinimum(1)
        self.replay_start_horizontalSlider.setMaximum(100)
        self.replay_start_horizontalSlider.setPageStep(1)
        self.replay_start_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.replay_start_horizontalSlider.setObjectName("replay_start_horizontalSlider")
        self.replay_step_title_label = QtWidgets.QLabel(self.replay_tab)
        self.replay_step_title_label.setGeometry(QtCore.QRect(10, 100, 51, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replay_step_title_label.sizePolicy().hasHeightForWidth())
        self.replay_step_title_label.setSizePolicy(sizePolicy)
        self.replay_step_title_label.setObjectName("replay_step_title_label")
        self.replay_end_lineEdit = QtWidgets.QLineEdit(self.replay_tab)
        self.replay_end_lineEdit.setGeometry(QtCore.QRect(70, 80, 81, 16))
        self.replay_end_lineEdit.setReadOnly(False)
        self.replay_end_lineEdit.setObjectName("replay_end_lineEdit")
        self.replay_pushButton = QtWidgets.QPushButton(self.replay_tab)
        self.replay_pushButton.setGeometry(QtCore.QRect(240, 130, 51, 20))
        self.replay_pushButton.setObjectName("replay_pushButton")
        self.replay_extract_checkBox = QtWidgets.QCheckBox(self.replay_tab)
        self.replay_extract_checkBox.setGeometry(QtCore.QRect(10, 130, 71, 21))
        self.replay_extract_checkBox.setChecked(False)
        self.replay_extract_checkBox.setTristate(False)
        self.replay_extract_checkBox.setObjectName("replay_extract_checkBox")
        self.replay_render_checkBox = QtWidgets.QCheckBox(self.replay_tab)
        self.replay_render_checkBox.setGeometry(QtCore.QRect(80, 130, 71, 21))
        self.replay_render_checkBox.setChecked(False)
        self.replay_render_checkBox.setObjectName("replay_render_checkBox")
        self.tabWidget.addTab(self.replay_tab, "")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.serial_port_comboBox.setCurrentIndex(0)
        self.chip_id_comboBox.setCurrentIndex(0)
        self.chip_frequency_comboBox.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(1)
        self.user_cmd_lineEdit.returnPressed.connect(self.user_cmd_pushButton.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BlackPearl @ Imperial"))
        self.system_groupBox.setTitle(_translate("MainWindow", "System Settings"))
        self.serial_port_title_label.setText(_translate("MainWindow", "Serial Port:"))
        self.serial_port_comboBox.setItemText(0, _translate("MainWindow", "Scanning"))
        self.serial_port_comboBox.setItemText(1, _translate("MainWindow", "Refresh"))
        self.serial_status_label.setText(_translate("MainWindow", "Serial Status:"))
        self.serial_status_title_label.setText(_translate("MainWindow", "Idle"))
        self.dac_groupBox.setTitle(_translate("MainWindow", "DAC (mV)"))
        self.dac_rst_label.setText(_translate("MainWindow", "Vg_rst"))
        self.dac_y_label.setText(_translate("MainWindow", "Vy"))
        self.dac_iv_label.setText(_translate("MainWindow", "Vcm_IV"))
        self.dac_ota_label.setText(_translate("MainWindow", "Vcm_OTA"))
        self.dac_int_label.setText(_translate("MainWindow", "V_integrate"))
        self.dac_read_pushButton.setText(_translate("MainWindow", "Read"))
        self.dac_write_pushButton.setText(_translate("MainWindow", "Write"))
        self.dac_reset_pushButton.setText(_translate("MainWindow", "Reset"))
        self.profile_groupBox.setTitle(_translate("MainWindow", "Chip Profile"))
        self.chip_delay_title_label.setText(_translate("MainWindow", "Clock Delay:"))
        self.chip_id_title_label.setText(_translate("MainWindow", "Chip ID:"))
        self.chip_id_comboBox.setItemText(0, _translate("MainWindow", "0"))
        self.chip_id_comboBox.setItemText(1, _translate("MainWindow", "1"))
        self.chip_id_comboBox.setItemText(2, _translate("MainWindow", "2"))
        self.chip_id_comboBox.setItemText(3, _translate("MainWindow", "3"))
        self.chip_id_comboBox.setItemText(4, _translate("MainWindow", "4"))
        self.chip_id_comboBox.setItemText(5, _translate("MainWindow", "5"))
        self.chip_id_comboBox.setItemText(6, _translate("MainWindow", "6"))
        self.chip_id_comboBox.setItemText(7, _translate("MainWindow", "7"))
        self.chip_id_comboBox.setItemText(8, _translate("MainWindow", "8"))
        self.chip_id_comboBox.setItemText(9, _translate("MainWindow", "9"))
        self.chip_id_comboBox.setItemText(10, _translate("MainWindow", "10"))
        self.chip_id_comboBox.setItemText(11, _translate("MainWindow", "11"))
        self.chip_id_comboBox.setItemText(12, _translate("MainWindow", "12"))
        self.chip_id_comboBox.setItemText(13, _translate("MainWindow", "13"))
        self.chip_id_comboBox.setItemText(14, _translate("MainWindow", "14"))
        self.chip_id_comboBox.setItemText(15, _translate("MainWindow", "15"))
        self.chip_id_comboBox.setItemText(16, _translate("MainWindow", "16"))
        self.chip_id_comboBox.setItemText(17, _translate("MainWindow", "17"))
        self.chip_id_comboBox.setItemText(18, _translate("MainWindow", "18"))
        self.chip_id_comboBox.setItemText(19, _translate("MainWindow", "19"))
        self.chip_id_comboBox.setItemText(20, _translate("MainWindow", "20"))
        self.chip_frequency_title_label.setText(_translate("MainWindow", "Clock Freq:"))
        self.chip_frequency_comboBox.setCurrentText(_translate("MainWindow", "10 MHz"))
        self.chip_frequency_comboBox.setItemText(0, _translate("MainWindow", "10 MHz"))
        self.chip_frequency_comboBox.setItemText(1, _translate("MainWindow", "50 MHz"))
        self.chip_frequency_comboBox.setItemText(2, _translate("MainWindow", "100 MHz"))
        self.chip_frequency_comboBox.setItemText(3, _translate("MainWindow", "200 MHz"))
        self.chip_frequency_comboBox.setItemText(4, _translate("MainWindow", "250 MHz"))
        self.rt_groupBox.setTitle(_translate("MainWindow", "Real-time Frame Acquisition"))
        self.rt_path_lineEdit.setText(_translate("MainWindow", "C:\\BlackPearl"))
        self.rt_path_title_label.setText(_translate("MainWindow", "Experiment Path:"))
        self.rt_path_toolButton.setText(_translate("MainWindow", "..."))
        self.rt_info_title_label.setText(_translate("MainWindow", "Information:"))
        self.rt_chip_id_title_label.setText(_translate("MainWindow", "Chip ID       (C_):"))
        self.rt_user_com_title_label.setText(_translate("MainWindow", "User Comment: (U_):"))
        self.rt_user_com_lineEdit.setToolTip(_translate("MainWindow", "<html><head/><body><p>Only alphabet, digital and underscore are allowed</p></body></html>"))
        self.rt_readout_pushButton.setText(_translate("MainWindow", "Readout"))
        self.rt_save_checkBox.setText(_translate("MainWindow", "Save"))
        self.rt_offset_pushButton.setText(_translate("MainWindow", "Offset"))
        self.rt_exp_id_title_label.setText(_translate("MainWindow", "Experiment ID (E_):"))
        self.rt_debug_checkBox.setText(_translate("MainWindow", "Debug"))
        self.rt_pixel_title_label.setText(_translate("MainWindow", "Pixel Readout Row/Col:"))
        self.rt_off_pushButton.setText(_translate("MainWindow", "OFF"))
        self.console_groupBox.setTitle(_translate("MainWindow", "Console"))
        self.console_clear_pushButton.setText(_translate("MainWindow", "clear"))
        self.user_cmd_groupBox.setTitle(_translate("MainWindow", "Debug Interface for Designer"))
        self.user_cmd_lineEdit.setText(_translate("MainWindow", "Input your command here"))
        self.user_cmd_pushButton.setText(_translate("MainWindow", "send"))
        self.concatenation_path_title_label.setText(_translate("MainWindow", "File Path:"))
        self.concatenation_path_lineEdit.setText(_translate("MainWindow", "C:\\BlackPearl"))
        self.concatenation_path_toolButton.setText(_translate("MainWindow", "..."))
        self.concatenation_pushButton.setText(_translate("MainWindow", "Concate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.file_tab), _translate("MainWindow", "File"))
        self.replay_path_title_label.setText(_translate("MainWindow", "Binary File Path:"))
        self.replay_path_lineEdit.setText(_translate("MainWindow", "C:\\BlackPearl"))
        self.replay_path_toolButton.setText(_translate("MainWindow", "..."))
        self.replay_check_pushButton.setText(_translate("MainWindow", "Check"))
        self.replay_start_lineEdit.setText(_translate("MainWindow", "1"))
        self.replay_start_title_label.setText(_translate("MainWindow", "Start:"))
        self.replay_end_title_label.setText(_translate("MainWindow", "End:"))
        self.replay_step_lineEdit.setText(_translate("MainWindow", "1"))
        self.replay_step_title_label.setText(_translate("MainWindow", "Step:"))
        self.replay_end_lineEdit.setText(_translate("MainWindow", "1"))
        self.replay_pushButton.setText(_translate("MainWindow", "Replay"))
        self.replay_extract_checkBox.setText(_translate("MainWindow", "Extract"))
        self.replay_render_checkBox.setText(_translate("MainWindow", "Render"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.replay_tab), _translate("MainWindow", "Replay"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

